-- Create a test user for password reset testing
INSERT INTO auth.users (
    id, 
    email, 
    email_confirmed_at, 
    created_at, 
    updated_at, 
    instance_id, 
    aud, 
    role,
    encrypted_password,
    email_confirm_token,
    confirmation_sent_at,
    recovery_sent_at,
    email_change_sent_at,
    last_sign_in_at,
    raw_app_meta_data,
    raw_user_meta_data,
    is_super_admin,
    phone,
    phone_confirmed_at,
    phone_change,
    phone_change_token,
    phone_change_sent_at,
    confirmed_at,
    email_change,
    email_change_token_current,
    email_change_confirm_status,
    banned_until,
    reauthentication_token,
    reauthentication_sent_at,
    is_sso_user,
    deleted_at
) VALUES (
    gen_random_uuid(),
    'test@example.com',
    NOW(),
    NOW(),
    NOW(),
    '00000000-0000-0000-0000-000000000000',
    'authenticated',
    'authenticated',
    '$2a$10$dummy.hash.for.testing.purposes.only',
    '',
    NOW(),
    NULL,
    NULL,
    NULL,
    '{"provider": "email", "providers": ["email"]}',
    '{"name": "Test User"}',
    false,
    NULL,
    NULL,
    '',
    '',
    NULL,
    NOW(),
    '',
    '',
    0,
    NULL,
    '',
    NULL,
    false,
    NULL
);

-- Also create a user profile for this test user
INSERT INTO public.user_profiles (
    id,
    email,
    full_name,
    role,
    created_at,
    updated_at
) VALUES (
    (SELECT id FROM auth.users WHERE email = 'test@example.com'),
    'test@example.com',
    'Test User',
    'user',
    NOW(),
    NOW()
);
