import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Calendar, Clock, Target, Star, TrendingUp } from 'lucide-react';
import { Link } from 'react-router-dom';
const WorkoutPlanCard = ({ plan, variant = 'default', showStats = true }) => {
    const getDifficultyStars = (difficulty) => {
        return Array.from({ length: 5 }, (_, i) => (_jsx(Star, { className: `h-4 w-4 ${i < difficulty ? 'text-yellow-400 fill-current' : 'text-gray-300'}` }, i)));
    };
    if (variant === 'compact') {
        return (_jsx(Link, { to: `/services/fitness-plans/${plan.id}`, children: _jsxs("div", { className: "bg-white rounded-lg shadow-md hover:shadow-lg transition-shadow duration-300 overflow-hidden cursor-pointer group", children: [_jsx("div", { className: "relative h-32", children: _jsx("img", { src: plan.image_url || "/images/placeholders/workout.jpg", alt: plan.title, className: "w-full h-full object-cover group-hover:scale-105 transition-transform duration-300" }) }), _jsxs("div", { className: "p-3", children: [_jsx("h3", { className: "font-semibold text-gray-900 truncate", children: plan.title }), _jsxs("div", { className: "flex items-center justify-between mt-2", children: [_jsxs("div", { className: "flex items-center text-xs text-gray-500", children: [_jsx(Calendar, { className: "h-3 w-3 mr-1" }), _jsxs("span", { children: [plan.duration, " weeks"] })] }), _jsxs("div", { className: "flex items-center text-xs text-gray-500", children: [_jsx(Clock, { className: "h-3 w-3 mr-1" }), _jsxs("span", { children: [plan.weekly_workouts, " days/week"] })] })] })] })] }) }));
    }
    if (variant === 'featured') {
        return (_jsx(Link, { to: `/services/fitness-plans/${plan.id}`, children: _jsxs("div", { className: "bg-white rounded-xl shadow-lg hover:shadow-xl transition-all duration-300 overflow-hidden cursor-pointer group", children: [_jsxs("div", { className: "relative h-64", children: [_jsx("img", { src: plan.image_url || "/images/placeholders/workout.jpg", alt: plan.title, className: "w-full h-full object-cover group-hover:scale-105 transition-transform duration-300" }), _jsx("div", { className: "absolute inset-0 bg-gradient-to-t from-black/70 via-transparent to-transparent" }), _jsx("div", { className: "absolute bottom-4 left-4 right-4", children: _jsx("h3", { className: "text-white font-bold text-xl mb-2", children: plan.title }) })] }), _jsxs("div", { className: "p-6", children: [_jsxs("div", { className: "grid grid-cols-3 gap-4 mb-4", children: [_jsxs("div", { className: "text-center", children: [_jsx("div", { className: "text-2xl font-bold text-green-600", children: plan.duration }), _jsx("div", { className: "text-sm text-gray-600", children: "Weeks" })] }), _jsxs("div", { className: "text-center", children: [_jsx("div", { className: "text-2xl font-bold text-blue-600", children: plan.weekly_workouts }), _jsx("div", { className: "text-sm text-gray-600", children: "Days/Week" })] }), _jsxs("div", { className: "text-center", children: [_jsxs("div", { className: "text-2xl font-bold text-purple-600", children: [plan.difficulty, "/5"] }), _jsx("div", { className: "text-sm text-gray-600", children: "Difficulty" })] })] }), showStats && plan.rating && (_jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { className: "flex items-center", children: [_jsx("div", { className: "flex mr-2", children: getDifficultyStars(plan.rating) }), _jsxs("span", { className: "text-sm text-gray-600", children: ["(", plan.reviewCount || 0, " reviews)"] })] }), plan.completionRate && (_jsxs("div", { className: "text-sm text-green-600 font-semibold", children: [plan.completionRate, "% completion rate"] }))] }))] })] }) }));
    }
    return (_jsx(Link, { to: `/services/fitness-plans/${plan.id}`, children: _jsxs("div", { className: "bg-white rounded-lg shadow-md hover:shadow-lg transition-shadow duration-300 overflow-hidden cursor-pointer group", children: [_jsx("div", { className: "relative h-48", children: _jsx("img", { src: plan.image_url || "/images/placeholders/workout.jpg", alt: plan.title, className: "w-full h-full object-cover group-hover:scale-105 transition-transform duration-300" }) }), _jsxs("div", { className: "p-4", children: [_jsx("h3", { className: "text-lg font-semibold text-gray-900 mb-2 line-clamp-1", children: plan.title }), showStats && (_jsxs("div", { className: "grid grid-cols-2 gap-4 mb-4", children: [_jsxs("div", { className: "flex items-center text-sm text-gray-600", children: [_jsx(Calendar, { className: "h-4 w-4 mr-2 text-green-600" }), _jsxs("span", { children: [plan.duration, " weeks"] })] }), _jsxs("div", { className: "flex items-center text-sm text-gray-600", children: [_jsx(Clock, { className: "h-4 w-4 mr-2 text-blue-600" }), _jsxs("span", { children: [plan.weekly_workouts, " days/week"] })] }), _jsxs("div", { className: "flex items-center text-sm text-gray-600", children: [_jsx(Target, { className: "h-4 w-4 mr-2 text-purple-600" }), _jsxs("span", { children: ["Difficulty ", plan.difficulty, "/5"] })] }), plan.estimated_calories_burn && (_jsxs("div", { className: "flex items-center text-sm text-gray-600", children: [_jsx(TrendingUp, { className: "h-4 w-4 mr-2 text-red-600" }), _jsxs("span", { children: [plan.estimated_calories_burn, " cal/week"] })] }))] })), showStats && (_jsxs("div", { className: "flex items-center justify-between pt-3 border-t border-gray-100", children: [plan.rating ? (_jsxs("div", { className: "flex items-center", children: [_jsx("div", { className: "flex mr-2", children: getDifficultyStars(plan.rating) }), _jsxs("span", { className: "text-sm text-gray-600", children: ["(", plan.reviewCount || 0, ")"] })] })) : (_jsx("div", { className: "text-sm text-gray-500", children: "No ratings yet" })), plan.completionRate && (_jsxs("div", { className: "text-sm text-green-600 font-semibold", children: [plan.completionRate, "% completion"] }))] })), showStats && plan.goals && plan.goals.length > 0 && (_jsx("div", { className: "mt-3", children: _jsxs("div", { className: "flex flex-wrap gap-1", children: [plan.goals.slice(0, 3).map((goal, index) => (_jsx("span", { className: "px-2 py-1 bg-green-100 text-green-800 text-xs rounded-full", children: goal }, index))), plan.goals.length > 3 && (_jsxs("span", { className: "px-2 py-1 bg-gray-100 text-gray-600 text-xs rounded-full", children: ["+", plan.goals.length - 3, " more"] }))] }) }))] })] }) }));
};
export default WorkoutPlanCard;
